### ISSUE TITLE
k2s status: Remove Addons' Status

### ISSUE THREAD

**Issue by jgriegershs** [Siemens-Healthineers/K2s#62]
### Current Behavior
When executing `k2s status [-o [wide|json]]`, the addons list and addon's enabled/disabled is also retrieved and displayed.

### Desired Behavior
When executing `k2s status [-o [wide|json]]`, the addons list and addon's enabled/disabled shall neither be retrieved nor displayed.

###  Reasoning
- addons are decoupled from *K2s* core functionality from a domain point of view
- addons should be technically decoupled from *K2s* core functionality since they can be added and removed independently from *K2s* releases
- with `k2s addons ls` and `k2s addons status <addon>`, retrieving and displaying addons and addon's status functionality is already available

**Comment by achimkist** [comment]
k2s test framework has to be modified, reverted changes for now to keep CI green

**Comment by achimkist** [comment]
there is a bug with current implementation because installation directory is not determind properly when k2s executable and ginkgo

panic: VERSION file not found

goroutine 1 [running]:
k2s/utils.determineInstallationDirectory()
        D:/a/K2s/K2s/pkg/k2s/utils/utilities.go:78 +0xf6
k2s/utils.init.0()
        D:/a/K2s/K2s/pkg/k2s/utils/utilities.go:37 +0xf

**Comment by achimkist** [comment]
there is a bug with current implementation because installation directory is not determind properly when k2s executable and ginkgo

panic: VERSION file not found

goroutine 1 [running]:
k2s/utils.determineInstallationDirectory()
D:/a/K2s/K2s/pkg/k2s/utils/utilities.go:78 +0xf6
k2s/utils.init.0()
D:/a/K2s/K2s/pkg/k2s/utils/utilities.go:37 +0xf
