### ISSUE TITLE
k2s uninstall: k2s CLI logs get deleted during uninstall

### ISSUE THREAD

**Issue by jgriegershs** [Siemens-Healthineers/K2s#67]
### Actual
During `k2s uninstall`, the *k2s* CLI logs get deleted from `c:\var\log\cli`. This makes post-install diagnoses harder.

### Expected
During `k2s uninstall`, the *k2s* CLI logs are preserved in `c:\var\log\cli`, similar to the `k2s.log` file.

**Comment by krotz-dieter** [comment]
Before cleaning up c:\var create a zip file with all the content of c:\var and copy it temp directory.
In addition a message with file location shall be shown.

**Comment by achimkist** [comment]
I0214 09:10:40.066499    4240 main.go:299] [09:10:40] Uninstalling Build Only Environment done.
I0214 09:10:40.520954    4240 main.go:314] ZipArchiveHelper : The process cannot access the file 'C:\var\log\ci\ci_stderr.log' because it is being used by 
I0214 09:10:40.526438    4240 main.go:314] another process.
I0214 09:10:40.526438    4240 main.go:314] At 
I0214 09:10:40.526438    4240 main.go:314] C:\Windows\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:697
