### ISSUE TITLE
For long term running, need I enable the automatic certification rotation function?

### ISSUE THREAD

**Issue by yanrunming** [Siemens-Healthineers/K2s#694]
I noticed the certification's expires has only 1 year
![cert-expires-1-year](https://github.com/user-attachments/assets/4fe7443a-0e7c-4d5b-9cbe-93cba7ebd961)

And there is no certification rotation in apiserver cmds.
![kube-apiserver-cmd](https://github.com/user-attachments/assets/6ff970cd-e23e-41ad-a730-4665eaf7b3cb)

Need I do something for long term running?

**Comment by krotz-dieter** [comment]
Yes, you need to update the certs if you keep the version longer active. But it is not recommended since K8s has roughly one year support for one version, better to upgrade always on newer versions. The certs need to be handled individually by every product how they want handle this, the certs can be updated with sudo kubeadm certs renew all on Kubemaster side.
Also --rotate-certificates for the kubelet is not activated, can also be activated by the product.
