### ISSUE TITLE
k2s addons enable exthttpaccess outputs an error

### ISSUE THREAD

**Issue by jgriegershs** [Siemens-Healthineers/K2s#88]
When running `k2s addons enable exthttpaccess`, an error occurs even though the exit code is 0:
```
⏳ [13:20:07] Obtaining IPs of active physical net adapters
⏳ [13:20:09] Creating nginx configuration file
⏳ [13:20:09] Downloading nginx executable
⏳ [13:20:09] Downloading 'https://nginx.org/download/nginx-1.23.2.zip' to 'C:\ws\k2sv2\bin\nginx\nginx.zip' (no proxy)
⏳ x nginx.exe
⏳ [13:20:10] Registering nginx service
⏳ [13:20:10] Service "ExtHttpAccess-nginx" installed successfully!
⏳ ExtHttpAccess-nginx: Unexpected status SERVICE_PAUSED in response to START control.
⏳
E0201 13:20:10.880625   12612 psexecutor.go:197] ExtHttpAccess-nginx: Unexpected status SERVICE_PAUSED in response to START control.
```

- [ ] fix the error
- [x] createn an e2e test for *exthttpaccess* addon

**Comment by gabriel-rosso** [comment]
The problem arises because there is already a process listening on the port 80. Just opening the browser an entering [http://localhost:80](http://localhost/) you'll see that the IIS server is accessed. 
A hard check for the ports 80 and 443 has to be introduced. If it is detected that they are already used then the alternative ports 8080 and 8443 must be used after user confirmation.
